# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: BLOG
description: >- # this means to ignore newlines until "baseurl:"
  Live A Colourful Life.
baseurl: "" # the subpath of the site
url: "https://solarwindrider.gitee.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slag: /
    - name: Work
    - name: Blog
    - name: Note
footer:
  show_powered_by: true
  contact:
    - name: Email
      value: 1149902816@qq.com
      link: 1149902816@qq.com
    - name: WeChat
      value: LiOH_24601
      link: "#"
    - name: QQ
      value: 1149902816
  follow:
    - name: GitHub
      link: https://github.com/solarwindrider
    - name: Gitee
      link: https://gitee.com/solarwindrider

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
